//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment()
        {
            this.project_equipment = new HashSet<project_equipment>();
        }
    
        public int equipmentID { get; set; }
        public string name { get; set; }
        public Nullable<int> modelID { get; set; }
        public string mark { get; set; }
        public Nullable<int> count { get; set; }
        public string note { get; set; }
    
        public virtual tech_models tech_models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_equipment> project_equipment { get; set; }
    }
}
