//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u0416457_systemEntities : DbContext
    {
        public u0416457_systemEntities()
            : base("name=u0416457_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<project_equipment> project_equipment { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<tech_brands> tech_brands { get; set; }
        public virtual DbSet<tech_models> tech_models { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
