//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u0516067_coopersystemEntities : DbContext
    {
        public u0516067_coopersystemEntities()
            : base("name=u0516067_coopersystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contacts> contacts { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<organizations> organizations { get; set; }
        public virtual DbSet<places> places { get; set; }
        public virtual DbSet<project_equipment> project_equipment { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<tech_brands> tech_brands { get; set; }
        public virtual DbSet<tech_models> tech_models { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
