//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_equipment
    {
        public int project_equipmentID { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> equipmentID { get; set; }
        public Nullable<int> count { get; set; }
        public string note { get; set; }
    
        public virtual equipment equipment { get; set; }
        public virtual project project { get; set; }
    }
}
